name: Integration tests

on:
  pull_request:
    branches: [ master, develop ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
